language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
before_script:
  - cargo install cargo-audit
  - cargo install cargo-tarpaulin
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo audit
  - cargo clippy -- -D warnings
  - cargo fmt --all -- --check
  - cargo tarpaulin --ignore-tests

  - cargo build
  - cargo test
  - cargo bench
